name: marqueer
description: Transform to "Marquee" from any widget.
version: 1.4.5
homepage: https://github.com/GeceGibi/marqueer

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  
flutter:
