name: marqueer
description: Transform to "Marquee" from any widget.
version: 1.4.4
homepage: https://github.com/GeceGibi/marqueer

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
flutter:
