name: marqueer
description: Transform to "Marquee" from any widget.
version: 2.0.1
homepage: https://github.com/GeceGibi/marqueer

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^7.0.0
  
flutter:
